### ISSUE TITLE
Please add `xonsh` and `xontrib` topics to the repository settings

### ISSUE THREAD

**Issue by anki-code** [doronz88/xontrib-fzf-completions#1]
Example:

<img width="332" alt="image" src="https://github.com/doronz88/xontrib-fzf-completions/assets/1708680/cd77ed0b-3561-4663-b81b-9690f366f4b9">

<img width="586" alt="image" src="https://github.com/doronz88/xontrib-fzf-completions/assets/1708680/e0de5f13-c463-40ba-9c39-8225d09c5dc9">

**Comment by doronz88** [comment]
added the relevant tags
